all: 
	gcc TADContabancaria.h TADCliente.h TADEndereco.h TADContabancaria.c TADCliente.c TADEndereco.c	 main.c -o exec
	./exec
clean:
	rm -rf *.o ./exec
	clear
run:
	LACliente.c	./Listas/LACliente.h	./Listas/LACliente.c	./Listas/LECliente.h	./Listas/LECliente.c ./Listas/LACelulaCliente.h